[package]
distribution = "slbeta6"
license = ["Apache-2.0"]
keywords = ["IT Operations/Cloud Services", "Cost/Freemium", "Vendor/Microsoft"]
org = "ballerinax"
name = "azure.qnamaker"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.1.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
